included:
  - Package.swift
  - Sources
  - Scripts
  - Tests

disabled_rules:
  - trailing_comma

file_length:
  warning: 500
  error: 1200

function_body_length:
  warning: 200
  error: 400

# Set a higher limit for type bodies in Sources since DatabaseManager
# is a complex class with multiple responsibilities
type_body_length:
  warning: 300
  error: 400

identifier_name:
  min_length: 3 # only warning

check_for_updates: false
