included:
  - Package.swift
  - Sources
  - Scripts
  - Tests

file_length:
  warning: 500
  error: 1200

function_body_length:
  warning: 200
  error: 400

identifier_name:
  min_length: 3 # only warning

check_for_updates: false
