name: Build

permissions:
  contents: write

on:
  workflow_run:
    workflows: ["Version"]
    branches: [main]
    types:
      - completed

jobs:
  build:
    name: Build
    runs-on: macos-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}


    steps:
      - uses: actions/checkout@v4

      - name: Set-up Swift
        uses: swift-actions/setup-swift@v2
        with:
          swift-version: '6.0'

      - name: Set-up Just
        uses: extractions/setup-just@v3

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: version
          run-id: ${{ github.event.workflow_run.id }}
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build
        run: just release

      - name: Find binary
        run: cp ./.build/release/kopya kopya

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build
          overwrite: true
          include-hidden-files: true
          path: |
            GITHUB_CHANGELOG.md
            version
            kopya
